### ISSUE TITLE
keeping track of my issues .... sort of ...

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/egret#64]
My to do:
* Finalize cleaning
1) germTempNum <- as.numeric(germTempGen) ... once Justin does
2) commonCols <- c("datasetID", "study", "entered.by", "genus", "species", "variety") 
3) look at everyone's source files to make sure they do not overwrite each other 

Lizzie is doing the following: general cleaning in cleaning folder, checking Fredi's code for USDA cleaning, checking others code when asked, work on study design -- including interactions

**Comment by lizzieinvancouver** [comment]
- [ ] Don't forget about missing data and other issues [as mentioned here](https://github.com/lizzieinvancouver/egret/issues/14#issuecomment-2211622590). I flagged the response and germ temp issues in other issues but the final few lines are all still open as best I know unless @DeirdreLoughnan is handling them elsewhere:

> Data grouping (study and figure)
> cousins10 - last data point for Table 5 seems to be for Figure 3
> yang18_2 - figure numbers seem to be mismatched; chill and germination data for Figure 5 similar to yang18_1 Figures 4 and 5
> wytsalucy21 - some data in exp4 should be for exp3
> 
> I also added a new file for new data entry as discussed https://github.com/lizzieinvancouver/egret/issues/23#issuecomment-2195238101, which file can be found as [analyses/input/missingData.csv](https://github.com/lizzieinvancouver/egret/blob/main/analyses/input/missingData.csv). I added one from tylkowski91, and also some tables from yang16_1 and yang20. Please double-check if valid or intentionally not included.

**Comment by lizzieinvancouver** [comment]
Remember to check meeting notes for what everyone is supposed to work on.

**Comment by lizzieinvancouver** [comment]
- [ ] Decisions for https://github.com/lizzieinvancouver/egret/issues/44
- [ ] Waiting on info to close https://github.com/lizzieinvancouver/egret/issues/15

**Comment by lizzieinvancouver** [comment]
- [ ] And check the cleanall.R code, as well assigning folks to check EACH source file.

**Comment by lizzieinvancouver** [comment]
- [ ] Issue #39 -- storage temp and duration
- [ ] #62 -- scarification

**Comment by lizzieinvancouver** [comment]
Issues #39 and #62 still on my plate ... but related to #39, I need help from someone to clean/check cleanStorage.R.

Also, I am working on:

- [ ] finalize cleancoordinates (issue #21)

**Comment by lizzieinvancouver** [comment]
See also #27 .... which should close at the same time.
